#!/usr/bin/env bash
# shellcheck disable=SC2086

domain=$1
subdomain=$2

get_record() {
    result=$(dig "$1.$domain" | awk '/ANSWER SECTION:/ {getline; print}')
    type=$(echo $result | awk '{print $4}')
    ip=$(echo $result | awk '{print $5}')
    echo "The subdomain $1 is a $type record and points to $ip"
}

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02
    do
        get_record $sub
    done
else
    get_record $subdomain
fi
